import type { CEFRLevel, LanguageCode } from '@/types';

export enum GeminiModel {
  FLASH_3 = '3-flash',
  FLASH_2_5 = '2.5-flash',
  FLASH_2_0 = '2.0-flash',
  FLASH_1_5 = '1.5-flash',
}

const MODEL_VALUES: Record<GeminiModel, string> = {
  [GeminiModel.FLASH_3]: 'gemini-3-flash-preview',
  [GeminiModel.FLASH_2_5]: 'gemini-2.5-flash',
  [GeminiModel.FLASH_2_0]: 'gemini-2.0-flash',
  [GeminiModel.FLASH_1_5]: 'gemini-1.5-flash',
};

export const getModel = (model: GeminiModel): string => {
  return MODEL_VALUES[model] ?? MODEL_VALUES[GeminiModel.FLASH_3];
};

export const models = [
  { label: GeminiModel.FLASH_3, value: MODEL_VALUES[GeminiModel.FLASH_3] },
  { label: GeminiModel.FLASH_2_5, value: MODEL_VALUES[GeminiModel.FLASH_2_5] },
  { label: GeminiModel.FLASH_2_0, value: MODEL_VALUES[GeminiModel.FLASH_2_0] },
  { label: GeminiModel.FLASH_1_5, value: MODEL_VALUES[GeminiModel.FLASH_1_5] },
];

export enum LanguagesISO639 {
  Indonesian = 'id',
  Afar = 'aa',
  Abkhazian = 'ab',
  Avestan = 'ae',
  Afrikaans = 'af',
  Akan = 'ak',
  Amharic = 'am',
  Aragonese = 'an',
  Arabic = 'ar',
  Assamese = 'as',
  Avaric = 'av',
  Aymara = 'ay',
  Azerbaijani = 'az',
  Bashkir = 'ba',
  Belarusian = 'be',
  Bulgarian = 'bg',
  Bihari = 'bh',
  Bislama = 'bi',
  Bambara = 'bm',
  Bengali = 'bn',
  Tibetan = 'bo',
  Breton = 'br',
  Bosnian = 'bs',
  'Catalan; Valencian' = 'ca',
  Chechen = 'ce',
  Chamorro = 'ch',
  Corsican = 'co',
  Cree = 'cr',
  Czech = 'cs',
  'Church Slavic' = 'cu',
  Chuvash = 'cv',
  Welsh = 'cy',
  Danish = 'da',
  German = 'de',
  'Divehi; Maldivian' = 'dv',
  Dzongkha = 'dz',
  Ewe = 'ee',
  Greek = 'el',
  English = 'en',
  Esperanto = 'eo',
  Spanish = 'es',
  Estonian = 'et',
  Basque = 'eu',
  Persian = 'fa',
  'Fula; Fulah; Pulaar; Pular' = 'ff',
  Finnish = 'fi',
  Fijian = 'fj',
  Faroese = 'fo',
  French = 'fr',
  'Western Frisian' = 'fy',
  Irish = 'ga',
  'Scottish Gaelic' = 'gd',
  Galician = 'gl',
  Guarani = 'gn',
  Gujarati = 'gu',
  Manx = 'gv',
  Hausa = 'ha',
  Hebrew = 'he',
  Hindi = 'hi',
  'Hiri Motu' = 'ho',
  Croatian = 'hr',
  Haitian = 'ht',
  Hungarian = 'hu',
  Armenian = 'hy',
  Herero = 'hz',
  Interlingua = 'ia',
  Interlingue = 'ie',
  Igbo = 'ig',
  Nuosu = 'ii',
  Inupiaq = 'ik',
  Ido = 'io',
  Icelandic = 'is',
  Italian = 'it',
  Inuktitut = 'iu',
  Japanese = 'ja',
  Javanese = 'jv',
  Georgian = 'ka',
  Kongo = 'kg',
  Kikuyu = 'ki',
  Kwanyama = 'kj',
  Kazakh = 'kk',
  Kalaallisut = 'kl',
  'Central Khmer' = 'km',
  Kannada = 'kn',
  Korean = 'ko',
  Kanuri = 'kr',
  Kashmiri = 'ks',
  Kurdish = 'ku',
  Komi = 'kv',
  Cornish = 'kw',
  Kyrgyz = 'ky',
  Latin = 'la',
  Luxembourgish = 'lb',
  Ganda = 'lg',
  Limburgan = 'li',
  Lingala = 'ln',
  Lao = 'lo',
  Lithuanian = 'lt',
  'Luba-Katanga' = 'lu',
  Latvian = 'lv',
  Malagasy = 'mg',
  Marshallese = 'mh',
  Maori = 'mi',
  Macedonian = 'mk',
  Malayalam = 'ml',
  Mongolian = 'mn',
  Marathi = 'mr',
  Malay = 'ms',
  Maltese = 'mt',
  Burmese = 'my',
  Nauru = 'na',
  'Norwegian Bokmål' = 'nb',
  'North Ndebele' = 'nd',
  Nepali = 'ne',
  Ndonga = 'ng',
  Dutch = 'nl',
  'Norwegian Nynorsk' = 'nn',
  Norwegian = 'no',
  'South Ndebele' = 'nr',
  Navajo = 'nv',
  Chichewa = 'ny',
  Occitan = 'oc',
  Ojibwe = 'oj',
  Oromo = 'om',
  Oriya = 'or',
  Ossetian = 'os',
  Panjabi = 'pa',
  Pali = 'pi',
  Polish = 'pl',
  Pashto = 'ps',
  Portuguese = 'pt',
  Quechua = 'qu',
  Romansh = 'rm',
  Rundi = 'rn',
  Romanian = 'ro',
  Russian = 'ru',
  Kinyarwanda = 'rw',
  Sanskrit = 'sa',
  Sardinian = 'sc',
  Sindhi = 'sd',
  'Northern Sami' = 'se',
  Sango = 'sg',
  Sinhala = 'si',
  Slovak = 'sk',
  Slovene = 'sl',
  Samoan = 'sm',
  Shona = 'sn',
  Somali = 'so',
  Albanian = 'sq',
  Serbian = 'sr',
  Swati = 'ss',
  'Southern Sotho' = 'st',
  Sundanese = 'su',
  Swedish = 'sv',
  Swahili = 'sw',
  Tamil = 'ta',
  Telugu = 'te',
  Tajik = 'tg',
  Thai = 'th',
  Tigrinya = 'ti',
  Turkmen = 'tk',
  Tagalog = 'tl',
  Tswana = 'tn',
  Tonga = 'to',
  Turkish = 'tr',
  Tsonga = 'ts',
  Tatar = 'tt',
  Twi = 'tw',
  Tahitian = 'ty',
  Uighur = 'ug',
  Ukrainian = 'uk',
  Urdu = 'ur',
  Uzbek = 'uz',
  Venda = 've',
  Vietnamese = 'vi',
  Volapük = 'vo',
  Walloon = 'wa',
  Wolof = 'wo',
  Xhosa = 'xh',
  Yiddish = 'yi',
  Yoruba = 'yo',
  Zhuang = 'za',
  Chinese = 'zh',
  Zulu = 'zu',
}

export const Languages = [
  { name: 'German', code: LanguagesISO639.German, icon: '🇩🇪' },
  { name: 'English', code: LanguagesISO639.English, icon: '🇬🇧' },
  { name: 'French', code: LanguagesISO639.French, icon: '🇫🇷' },
  { name: 'Spanish', code: LanguagesISO639.Spanish, icon: '🇪🇸' },
  { name: 'Italian', code: LanguagesISO639.Italian, icon: '🇮🇹' },
  { name: 'Portuguese', code: LanguagesISO639.Portuguese, icon: '🇵🇹' },
  { name: 'Dutch', code: LanguagesISO639.Dutch, icon: '🇳🇱' },
  { name: 'Swedish', code: LanguagesISO639.Swedish, icon: '🇸🇪' },
  { name: 'Polish', code: LanguagesISO639.Polish, icon: '🇵🇱' },
  { name: 'Romanian', code: LanguagesISO639.Romanian, icon: '🇷🇴' },
  { name: 'Czech', code: LanguagesISO639.Czech, icon: '🇨🇿' },
  { name: 'Danish', code: LanguagesISO639.Danish, icon: '🇩🇰' },
  { name: 'Hungarian', code: LanguagesISO639.Hungarian, icon: '🇭🇺' },
  { name: 'Finnish', code: LanguagesISO639.Finnish, icon: '🇫🇮' },
  { name: 'Slovak', code: LanguagesISO639.Slovak, icon: '🇸🇰' },
  { name: 'Slovenian', code: LanguagesISO639.Slovene, icon: '🇸🇮' },
  { name: 'Estonian', code: LanguagesISO639.Estonian, icon: '🇪🇪' },
  { name: 'Greek', code: LanguagesISO639.Greek, icon: '🇬🇷' },
  { name: 'Bulgarian', code: LanguagesISO639.Bulgarian, icon: '🇧🇬' },
  { name: 'Croatian', code: LanguagesISO639.Croatian, icon: '🇭🇷' },
  { name: 'Lithuanian', code: LanguagesISO639.Lithuanian, icon: '🇱🇹' },
  { name: 'Latvian', code: LanguagesISO639.Latvian, icon: '🇱🇻' },
  { name: 'Maltese', code: LanguagesISO639.Maltese, icon: '🇲🇹' },
  { name: 'Norwegian', code: LanguagesISO639.Norwegian, icon: '🇳🇴' },
  { name: 'Turkish', code: LanguagesISO639.Turkish, icon: '🇹🇷' },
  { name: 'Ukrainian', code: LanguagesISO639.Ukrainian, icon: '🇺🇦' },
  { name: 'Hebrew', code: LanguagesISO639.Hebrew, icon: '🇮🇱' },
  { name: 'Hindi', code: LanguagesISO639.Hindi, icon: '🇮🇳' },
  { name: 'Indonesian', code: LanguagesISO639.Indonesian, icon: '🇮🇩' },
  { name: 'Korean', code: LanguagesISO639.Korean, icon: '🇰🇷' },
  { name: 'Malay', code: LanguagesISO639.Malay, icon: '🇲🇾' },
  { name: 'Vietnamese', code: LanguagesISO639.Vietnamese, icon: '🇻🇳' },
  { name: 'Chinese', code: LanguagesISO639.Chinese, icon: '🇨🇳' },
  { name: 'Japanese', code: LanguagesISO639.Japanese, icon: '🇯🇵' },
  { name: 'Urdu', code: LanguagesISO639.Urdu, icon: '🇵🇰' },
  { name: 'Bengali', code: LanguagesISO639.Bengali, icon: '🇧🇩' },
  { name: 'Russian', code: LanguagesISO639.Russian, icon: '🇷🇺' },
  { name: 'Arabic', code: LanguagesISO639.Arabic, icon: '🇸🇦' },
].sort((a, b) => a.name.localeCompare(b.name));

export const CEFR_LEVELS: { level: CEFRLevel; name: string; description: string }[] = [
  { level: 'A1', name: 'Beginner', description: 'Can understand basic phrases' },
  { level: 'A2', name: 'Elementary', description: 'Can communicate in simple tasks' },
  { level: 'B1', name: 'Intermediate', description: 'Can deal with most travel situations' },
  { level: 'B2', name: 'Upper Intermediate', description: 'Can interact with fluency' },
  { level: 'C1', name: 'Advanced', description: 'Can express ideas fluently' },
  { level: 'C2', name: 'Proficient', description: 'Can understand virtually everything' },
];

export const DEFAULT_SETTINGS = {
  userLanguage: 'en' as LanguageCode,
  topicLanguage: 'es' as LanguageCode,
  level: 'A2' as CEFRLevel,
  theme: 'system' as const,
};

export const Colors = {
  light: {
    text: '#11181C',
    textSecondary: '#687076',
    background: '#FFFFFF',
    card: '#F4F4F5',
    border: '#E4E4E7',
    primary: '#2563EB',
    primaryText: '#FFFFFF',
    success: '#16A34A',
    error: '#DC2626',
  },
  dark: {
    text: '#ECEDEE',
    textSecondary: '#9BA1A6',
    background: '#151718',
    card: '#27272A',
    border: '#3F3F46',
    primary: '#3B82F6',
    primaryText: '#FFFFFF',
    success: '#22C55E',
    error: '#EF4444',
  },
};
